name: Generate Results Index

on:
  push:
    paths:
      - 'doc/results/*.csv'  # Trigger on CSV changes

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Generate results-index.json
        run: |
          files=$(ls doc/results/*.csv 2>/dev/null || echo "")
          files_json=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')
          echo "{\"csvFiles\": $files_json}" > doc/results/results-index.json

      - name: Commit and push results-index.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add doc/results/results-index.json
      
          if ! git diff --cached --quiet; then
            git commit -m "Update results-index.json"
            git pull --rebase origin main
            git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
            git push origin main
          else
            echo "No changes to commit, skipping push."
          fi
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
