name: Update Trivia

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-trivia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Run trivia fetcher
        run: node trivia-proxy.js
        env:
          NINJA_API_KEY: ${{ secrets.NINJA_API_KEY }}

      - name: Commit & Push updated trivia.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
          git add public/trivia.json
          git commit -m "Update trivia" || echo "No changes to commit"
          git push
