name: Update Results Index

on:
  push:
    paths:
      - 'doc/results/*.csv'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate results-index.json
        run: |
          files=$(ls doc/results/*.csv || echo "")
          files_json=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')
          echo "{\"csvFiles\": $files_json}" > doc/results/results-index.json

      - name: Commit results-index.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add doc/results/results-index.json
          git diff --cached --quiet || git commit -m "Update results-index.json"
          git push
